### ISSUE TITLE
ratpack-kotlin-dsl: KServerSpec should allow registry configuration

### ISSUE THREAD

**Issue by jterhune** [drmaas/ratpack-kotlin#26]
The kotlin DSL `KServerSpec` only allows configuration of a guice registry. It would be nice to expose the RegistrySpec to allow more fine-grained configuration of the registry is possible.

Similar to this: https://github.com/ratpack/example-ratpack-gradle-kotlin-app/blob/master/src/main/kotlin/ratpack/example/kotlin/Helpers.kt

**Comment by drmaas** [comment]
Closed in https://github.com/drmaas/ratpack-kotlin/pull/29
