### ISSUE TITLE
Kotlin DSL vs Groovy

### ISSUE THREAD

**Issue by davidsowerby** [drmaas/ratpack-kotlin#7]
I am very new to Ratpack, and working through the 'Learning Ratpack' book - most of the examples in that are understandably in Groovy.  I prefer Kotlin, however - how close do you believe your Kotlin DSL is to the Groovy version provided by Ratpack?

**Comment by drmaas** [comment]
Hi David - 

Thanks for you interest! My goal is to provide 100% parity. That being said, Ratpack is evolving over time and I may not be aware of newly added methods to the Groovy DSL.

I have an open issue, when I have time, to test all of the kotlin DSL methods using the excellent kotlintest framework. 

I encourage you to play with this DSL, and feel free to provide any and all feedback on problem areas. I also encourage you to submit issues or PRs for features that you might find valuable. I don't have as much time as I'd like to get to everything I want to get to, so I'd love to have help!

Dan

**Comment by davidsowerby** [comment]
Ok, great,  I'm happy to provide feedback - I understand the problem of finding enough time :-)
